### ISSUE TITLE
Exception: cannot get wt

### ISSUE THREAD

**Issue by Pcrosser** [rkwyu/gofile-dl#6]
Keep getting the following error:

C:\Users\go\gofile-dl>run.py https://gofile.io/d/--
[2024-12-05 010:06:55,832][        update_token()][INFO    ]: updated token: ---
Traceback (most recent call last):
  File "C:\Users\go\gofile-dl\run.py", line 143, in <module>
    GoFile().execute(dir=dir, url=args.url, password=args.password)
  File "C:\Users\go\gofile-dl\run.py", line 107, in execute
    self.execute(dir=dir, content_id=url.split("/")[-1], password=password)
  File "C:\Users\go\gofile-dl\run.py", line 77, in execute
    self.update_wt()
  File "C:\Users\go\gofile-dl\run.py", line 72, in update_wt
    raise Exception("cannot get wt")
Exception: cannot get wt

**Comment by rkwyu** [comment]
modified function "update_wt" to adapt the changes from gofile.io
